### ISSUE TITLE
Test failure with xmltodict 1.0.2

### ISSUE THREAD

**Issue by dotlambda** [exxamalte/python-aio-georss-client#63]
After updating xmltodict to version 1.0.2 I get
```
============================= test session starts ==============================
platform linux -- Python 3.13.9, pytest-8.4.2, pluggy-1.6.0
rootdir: /build/source
configfile: pyproject.toml
testpaths: tests
plugins: asyncio-1.2.0
asyncio: mode=Mode.STRICT, debug=False, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
collected 54 items                                                             

tests/test_feed.py ..F............                                       [ 27%]
tests/test_feed_entry.py ...                                             [ 33%]
tests/test_feed_manager.py ...                                           [ 38%]
tests/test_geometries.py ..........                                      [ 57%]
tests/test_georss_distance_helper.py .............                       [ 81%]
tests/test_xml_parser.py ..........                                      [100%]

=================================== FAILURES ===================================
____________________________ test_update_ok_feed_3 _____________________________

mock_aioresponse = <aioresponses.core.aioresponses object at 0x7ffff4e9fd90>

    @pytest.mark.asyncio
    async def test_update_ok_feed_3(mock_aioresponse):
        """Test updating feed is ok."""
        mock_aioresponse.get(
            "http://test.url/testpath",
            status=HTTPStatus.OK,
            body=load_fixture("generic_feed_3.xml"),
        )
    
        async with aiohttp.ClientSession(loop=asyncio.get_running_loop()) as websession:
            feed = MockGeoRssFeed(
                websession, HOME_COORDINATES_1, "http://test.url/testpath"
            )
>           status, entries = await feed.update()
                              ^^^^^^^^^^^^^^^^^^^

tests/test_feed.py:113: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
aio_georss_client/feed.py:73: in update
    status, rss_data = await self._fetch()
                       ^^^^^^^^^^^^^^^^^^^
aio_georss_client/feed.py:107: in _fetch
    feed_data = parser.parse(text)
                ^^^^^^^^^^^^^^^^^^
aio_georss_client/xml_parser/__init__.py:107: in parse
    parsed_dict = xmltodict.parse(
/nix/store/1hqns6ndx61kagrxc3y1i471q775rjzw-python3.13-xmltodict-1.0.2/lib/python3.13/site-packages/xmltodict.py:368: in parse
    parser.Parse(xml_input, True)
./Modules/pyexpat.c:482: in EndElement
    ???
/nix/store/1hqns6ndx61kagrxc3y1i471q775rjzw-python3.13-xmltodict-1.0.2/lib/python3.13/site-packages/xmltodict.py:138: in endElement
    self.item = self.push_data(self.item, name, item)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/nix/store/1hqns6ndx61kagrxc3y1i471q775rjzw-python3.13-xmltodict-1.0.2/lib/python3.13/site-packages/xmltodict.py:159: in push_data
    result = self.postprocessor(self.path, key, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aio_georss_client/xml_parser/__init__.py:82: in postprocessor
    point_coordinates = XmlParser._process_coordinates(value)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

value = {'#text': '-34.937663524 148.597260613 -34.9377026399999 148.597169138 -34.9377002169999 148.59708737 -34.937694598999...597501208 -34.9375217259999 148.597421427 -34.937663524 148.597260613', '@xmlns': {'': 'http://www.georss.org/georss'}}

    @staticmethod
    def _process_coordinates(value: str) -> list[float]:
        """Turn white-space separated list of numbers into list of floats."""
>       coordinate_values = value.split()
                            ^^^^^^^^^^^
E       AttributeError: 'dict' object has no attribute 'split'

aio_georss_client/xml_parser/__init__.py:98: AttributeError
=========================== short test summary info ============================
FAILED tests/test_feed.py::test_update_ok_feed_3 - AttributeError: 'dict' object has no attribute 'split'
========================= 1 failed, 53 passed in 1.15s =========================
```

**Comment by mweinelt** [comment]
Bisected to https://github.com/martinblech/xmltodict/commit/f0322e578184421693434902547f330f4f0a44c3 in v1.0.0 of xmltodict.
